Reward - Reward Confim Page
isd-sgcu/firstdate-rpkm67-frontend pull request #13
Opened 2024-06-29 11:19 UTC by dunkdunkdunk

1. reward page
2. confirmation modal
3. Two circle menu as a component

2024-06-29 14:47 UTC, TeeGoood requested changes
คราวหลังจะสร้าง branch ใหม่ให้
git checkout main
git pull
ก่อนเเล้วค่อยสร้าง branch ใหม่จาก main

เเล้วอย่าลืม pnpm lint:fix ด้วยนะ

2024-06-29 14:47 UTC, TeeGoood commented on src/app/reward/page.tsx
> +              fill="white"
ให้ใช้ Image component เเทน inline-svg

2024-06-30 04:24 UTC, dunkdunkdunk commented
ขออภัยครับพี่ ไม่ได้ branch จาก main 

แก้ inline svg แล้วครับ

2024-06-30 09:42 UTC, TeeGoood approved these changes
LGTM!!

2024-06-30 09:43 UTC, merged