Chin fe/fdr 41 home
isd-sgcu/firstdate-rpkm67-frontend pull request #28
Opened 2024-07-07 14:48 UTC by jaroonro

feat: ui, reder user data, link to another page

2024-07-08 07:49 UTC, TeeGoood requested changes
pnpm lint:fix ด้วยนะ

2024-07-08 07:49 UTC, TeeGoood commented on public/home/smurfcat.png
ไม่ใช้เเล้วลบออกด้วย

2024-07-08 07:49 UTC, TeeGoood commented on src/app/home/page.tsx
> +                            src={user?.photoUrl}
อันนี้ให้เพิ่ม condition ถ้าไม่มีรูปให้เอา placeholder มาเเปะ
ซึ่ง file placeholder อยู่ใน main เเล้ว
/public/placeholder.svg

2024-07-08 07:49 UTC, TeeGoood commented on src/app/home/page.tsx
> +                <CustomButton varient='first-date' disabled = {(user && hasEvent(user.check_ins, "CUFD2024"))?true:false}>
condition ของ firstdate 
- ถ้ายังไม่ถึงวันงาน : ให้ขึ้น popup บอก ซึ่งเดี๋ยว design popup กำลังทำอยู่
- ถ้าถึงเเล้ว: ให้ไปหน้า /fistdate/home

2024-07-08 07:49 UTC, TeeGoood commented on src/app/home/page.tsx
> +                <CustomButton varient='rub-peun' disabled = {(user && hasEvent(user.check_ins, "RPKM2024"))?true:false}>
condition คือ 
- ถ้ายังไม่ถึงวันลงทะเบียน: ให้ไปหน้า /coming-soon
- ถ้าถึงเเล้ว: ยังไม่ต้องทำอะไร

2024-07-08 07:49 UTC, TeeGoood commented on src/app/home/page.tsx
> +                    </button>
ปุ่มนี้เเยกเป็น component อื่นได้มั้ย เอาทั้ง 2 ปุ่มเลย 
qr เเละ edit

2024-07-08 07:49 UTC, TeeGoood commented on src/app/home/page.tsx
> +                    <Link href="/" className="w-[4.8vh] h-[4.8vh] rounded-full flex justify-center items-center shadow-[0px_3px_4px_.5px_#00000048] hover:scale-105">
อันนี้ให้ link ไปหน้า edit

2024-07-08 07:49 UTC, TeeGoood commented on src/app/map/page.tsx
อันนี้เเก้ทำไมหรอ ช่วยเเก้กลับไปให้เหมือน main ได้มั้ย

2024-07-08 07:49 UTC, TeeGoood commented on src/app/test/page.tsx
ช่วยลบ test ออกตอน commit ด้วยนะ

2024-07-08 07:49 UTC, TeeGoood commented on src/components/home/CustomButton.tsx
สีเราใส่มาใน tailwind config เเล้วนะ
เอามาใช้เเทนหน่อย

2024-07-08 07:49 UTC, TeeGoood commented on src/components/home/QrCodePopup.tsx
หน้านี้ขอให้ gen QR code ตาม user.id ให้หน่อยนะ
เอา lib มาใช้ได้เลย

2024-07-08 07:51 UTC, TeeGoood requested changes

2024-07-08 07:51 UTC, TeeGoood commented on src/components/home/CustomButton.tsx
> +    const eb = ()=>{
e-book เวลากดให้ยิง api ไปที่ /count ด้วย

2024-07-09 10:44 UTC, TeeGoood commented on src/components/home/CustomButton.tsx
> +  };
- สร้าง file count.ts ใน folder utils
- ให้เอา code ที่ยิง request ไปไว้ใน function createCount เเล้ว export มาใช้ในนี้
- มันต้องเอา accessToken ไปใส่ header authorization ด้วยลองไปดูตัวอย่างใน user.ts
- ตอนนี้ api เหมือนจะมีปัญหาอยู่ ลองเเก้ตามที่ review ไปก่อนนะ

2024-07-09 10:56 UTC, TeeGoood commented on src/components/home/QrCodeModal.tsx
> +  }, []);
code นี้มันจำเป็นด้วยหรอ คือปกติ size ของหน้าจอ user มันก็ไม่ได้เปลี่ยนอยู่เเล้วรึปล่าว

2024-07-09 10:57 UTC, TeeGoood commented on src/components/home/QrCodeModal.tsx
> +  const [viewportHeight, setViewportHeight] = useState<number>(0.25*window.innerHeight);
state นี้ไม่น่าจะต้องใช้นะถ้าเราไม่เอา code useEffect ข้างล่างเเล้ว

2024-07-09 10:57 UTC, TeeGoood commented on src/components/home/QrCodeModal.tsx
> +              width: viewportHeight
อันนี้ใช้เป็น 0.25*window.innerHeight ไปเลยได้มั้ย ?

2024-07-09 12:23 UTC, jaroonro commented on src/components/home/QrCodeModal.tsx
> +  }, []);
อันนี้เผื่อสำหรับหมุนจอ แนวตั้ง/นอน

2024-07-09 13:45 UTC, TeeGoood approved these changes

2024-07-09 13:53 UTC, merged