Don fe/fdr 60 map page add assets and navigate button
isd-sgcu/firstdate-rpkm67-frontend pull request #33
Opened 2024-07-08 06:03 UTC by ThanaphomH

2024-07-08 07:19 UTC, TeeGoood requested changes

2024-07-08 07:19 UTC, TeeGoood commented on src/app/map/page.tsx
>          <Icon
- profile icon ต้องทำด้วยหรอ

2024-07-18 08:41 UTC, ThanaphomH commented
assets เรียบร้อย

2024-07-18 08:42 UTC, TeeGoood approved these changes

2024-07-18 08:46 UTC, merged