Chin fe/fdr 67 sidebar and navbar
isd-sgcu/firstdate-rpkm67-frontend pull request #42
Opened 2024-07-11 13:24 UTC by jaroonro

sidebar/navbar เหลือ function ของปุ่มต่าง ๆ ตอนใช้ใส่แค่ <Navbar/>

2024-07-12 09:58 UTC, D33102 commented on src/components/rpkm/Navbar.tsx
> +      <div className="w-full h-[63px] bg-[#313131] flex justify-between items-center px-5">
เราใช้ h-16 ดีกว่ามั้ยย  tailwind มันมี default ให้อยู่แล้วอ่าา

2024-07-12 09:58 UTC, D33102 commented on src/components/rpkm/Navbar.tsx
> +          className="w-[28px] h-[26px] bg-white flex flex-col justify-evenly items-center"
ใช้ w-7 กะ h-6 ก้ได้ๆ ถ้าอันไหนมี config ใน tailwind อยู่แล้วก็ใช้เลยหรือว่าถ้ามันใกล้เคียงก็ใช้ได้ ทำกับทุกไฟล์เลยนะๆ

2024-07-12 09:58 UTC, D33102 commented on src/components/rpkm/Navbar.tsx
> +          <div className="w-[16px] h-[2.6px] bg-black" />
อันนี้เราใช้ iconify ได้นะๆ
https://icon-sets.iconify.design/?query=hamburger

2024-07-12 10:00 UTC, D33102 commented on src/components/rpkm/Navbar.tsx
> +          <div className="w-[16px] h-[2.6px] bg-black" />
อันนี้ใช้ iconify ได้นะะ
https://icon-sets.iconify.design/?query=hamburger

2024-07-12 18:43 UTC, punchanabu approved these changes
กดไว้ก่อน

2024-07-12 18:43 UTC, punchanabu commented on src/components/rpkm/Sidebar.tsx
> +import UserInfo from './Sidebar/UserInfo';
เปลี่ยนเป็น `import UserInfo from '@/components/rpkm/Sidebar/UserInfo`

2024-07-12 18:43 UTC, punchanabu commented on src/components/rpkm/Sidebar.tsx
> +import Menu from './Sidebar/Menu';
เปลี่ยนเป็น `import Menu from '@/components/SideBar/Menu`

2024-07-12 18:43 UTC, punchanabu commented on src/components/rpkm/Sidebar/Menu.tsx
เราจะรีวิวรวมๆนะ เราเห็น Chin ใช้ `vh` เยอะมาก ซึ่งส่วนตัวเราคิดว่าถ้าใช้ [tailwind unit](https://tailwindcss.com/docs/width) จะดีกว่า เช่นพวก `w-5 h-5` ไรงี้หรืออย่าง text ก็แบบ `text-xl text-2xl` ลองเทียบ scale ดู

2024-07-12 18:43 UTC, punchanabu commented on src/components/rpkm/Sidebar/UserInfo.tsx
อันนี้ด้วย

2024-07-12 18:45 UTC, punchanabu requested changes

2024-07-12 18:45 UTC, punchanabu commented on src/components/rpkm/Navbar.tsx
อันนี้ด้วย

2024-07-12 18:46 UTC, punchanabu commented
อย่าลืม run `pnpm lint:fix` ด้วยนะ

2024-07-14 15:39 UTC, punchanabu approved these changes
Good 👍

2024-07-17 14:38 UTC, merged