Sun/fdr 74 baancard
isd-sgcu/firstdate-rpkm67-frontend pull request #51
Opened 2024-07-13 04:18 UTC by Kchanatipz

2024-07-13 22:09 UTC, TeeGoood requested changes

2024-07-13 22:09 UTC, TeeGoood commented on src/components/rpkm/baanCard.tsx
> +export default function page({
change to BaanCard

2024-07-13 22:09 UTC, TeeGoood commented on src/components/rpkm/baanCard.tsx
change filename to BaanCard.tsx

2024-07-13 22:09 UTC, TeeGoood commented on src/components/rpkm/baanCard.tsx
> +        </Link>
- อันนี้ไม่ใช่ link นะถ้า click เเล้วมันจะเปิด modal ขึ้นมา 
- ให้มัน click ได้ทั้ง card เลยไม่ต้องเเค่ตรงนี้จุดเดียว

2024-07-13 22:09 UTC, TeeGoood commented on src/components/rpkm/baanCard.tsx
> +        src={image ? image : baanExampleImg}
ให้เอา placeholder เเบบใน figma มาใช้เเทน

2024-07-14 09:40 UTC, Kchanatipz commented on src/components/rpkm/baanCard.tsx
> +        src={image ? image : baanExampleImg}
<img width="196" alt="Screenshot 2567-07-14 at 16 40 45" src="https://github.com/user-attachments/assets/98c736de-a748-48dc-88bf-15f3df62b34c">
อันนี้ช่ะ

2024-07-14 09:42 UTC, Kchanatipz commented on src/components/rpkm/baanCard.tsx
> +        </Link>
อ๋อคือ ให้กุเอาmodalมาใช้ละใส่contentนู่นนี่เช้าไปด้วยใช่มะ

2024-07-14 14:52 UTC, closed without merging