Dunk fe/fdr 31 coming soon page
isd-sgcu/firstdate-rpkm67-frontend pull request #8
Opened 2024-06-27 15:50 UTC by dunkdunkdunk

coming soon page finalize

2024-06-28 03:43 UTC, TeeGoood requested changes

2024-06-28 03:43 UTC, TeeGoood commented on src/components/Welcome.tsx
> +    <div className="absolute top-20 text-center font-season italic">
- ช่วย absolute กับ top-20 ออกหน่อย
  ตรงนี้พี่พลาดเองเดี๋ยวไปเเก้ component border ออกให้

2024-06-29 08:29 UTC, dunkdunkdunk commented
อันนี้ได้มั้ยครับพี่
1. แก้ absolute
2. เพิ่ม cn

2024-06-29 13:35 UTC, TeeGoood approved these changes
เยี่ยมมาก 
พี่ย้าย folder lib ไปอยู่ใร src folder นะ

2024-06-29 13:35 UTC, merged

2024-06-30 02:53 UTC, dunkdunkdunk commented
โอเครครับ ขอบคุณมากครับพี่